name: CI
on: [push]
jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: print root
        run: exit 1

  deploy:
    name: 'deploy'
    # needs: test
    runs-on: ubuntu-latest
    steps:
      # https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/droplet.key
          chmod 600 ~/.ssh/droplet.key
          cat >>~/.ssh/config <<END
          Host droplet
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/droplet.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSHKEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: print root
        run: ssh droplet 'whoami'

      - name: update repo
        run: ssh droplet 'cd /repos/beachstats_scraper/ && git pull && npm install'

      - name: build repo
        run: ssh droplet 'cd /repos/beachstats_scraper/ && npm run build'

      - name: copy .env
        run: ssh droplet 'cp /repos/beachstats_scraper/.env /repos/beachstats_scraper/build/'

      - name: reload pm2 process
        run: ssh droplet 'source ~/.nvm/nvm.sh && cd /repos/beachstats_scraper/ && pm2 reload pm2/prod.config.js'
